version: "3.8"

services:
    traefik:
        image: traefik:v3.0
        container_name: traefik
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080" # Traefik dashboard (optional, can be disabled in production)
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
            - ./traefik/dynamic:/etc/traefik/dynamic:ro
            - traefik-certificates:/certificates
        networks:
            - web
        environment:
            - TRAEFIK_API_DASHBOARD=true
            - TRAEFIK_API_INSECURE=true # Set to false in production
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
            - "traefik.http.routers.dashboard.tls=true"
            - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

    mariadb:
        image: mariadb:10.11
        container_name: wordpress-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - backend
        command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
            --max_connections=200
            --innodb-buffer-pool-size=256M

    wordpress:
        image: wordpress:6.7-fpm-alpine
        container_name: wordpress-app
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST: mariadb
            WORDPRESS_DB_NAME: ${DB_NAME}
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX:-wp_}
            WORDPRESS_DEBUG: ${WP_DEBUG:-false}
        volumes:
            - wp_data:/var/www/html
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - web
            - backend
        depends_on:
            - mariadb
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.wordpress.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.wordpress.tls=true"
            - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
            - "traefik.http.services.wordpress.loadbalancer.server.port=9000"

    nginx:
        image: nginx:alpine
        container_name: wordpress-nginx
        restart: unless-stopped
        volumes:
            - wp_data:/var/www/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - web
        depends_on:
            - wordpress
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.nginx.tls=true"
            - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"

volumes:
    db_data:
        driver: local
    wp_data:
        driver: local
    traefik-certificates:
        driver: local

networks:
    web:
        external: true
    backend:
        driver: bridge
