http:
    middlewares:
        https-redirect:
            redirectScheme:
                scheme: https
                permanent: true

    routers:
        http-catchall:
            rule: hostregexp(`{host:.+}`)
            entrypoints:
                - web
            middlewares:
                - https-redirect
            service: api@internal
