name: Deploy WordPress to VPS

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            environment:
                description: "Deployment environment"
                required: true
                default: "production"
                type: choice
                options:
                    - production
                    - staging

env:
    ANSIBLE_HOST_KEY_CHECKING: False

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment || 'production' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install Ansible and dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install ansible docker

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  chmod 700 ~/.ssh
                  # Add host to known_hosts
                  ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
                  # Setup SSH key with proper formatting
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  # Test the key format
                  if ! ssh-keygen -y -f ~/.ssh/id_rsa > /dev/null 2>&1; then
                    echo "SSH key format validation failed. Trying alternative setup..."
                    # Alternative: Use SSH agent
                    eval $(ssh-agent -s)
                    echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
                  else
                    echo "SSH key format is valid"
                  fi

            - name: Test SSH connection
              run: |
                  echo "Testing SSH connection..."
                  ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful'"

            - name: Verify Ansible installation
              run: |
                  ansible --version
                  ansible-galaxy collection install community.docker --force

            - name: Run Ansible deployment
              working-directory: ./ansible
              run: |
                  ansible-playbook playbooks/deploy.yml \
                    -i "${{ secrets.VPS_HOST }}," \
                    -e ansible_host=${{ secrets.VPS_HOST }} \
                    -e ansible_user=${{ secrets.VPS_USER }} \
                    -e domain_name=${{ secrets.DOMAIN_NAME }} \
                    -e acme_email=${{ secrets.ACME_EMAIL }} \
                    -e db_root_password=${{ secrets.DB_ROOT_PASSWORD }} \
                    -e db_name=${{ secrets.DB_NAME }} \
                    -e db_user=${{ secrets.DB_USER }} \
                    -e db_password=${{ secrets.DB_PASSWORD }} \
                    -e wp_table_prefix=${{ secrets.WP_TABLE_PREFIX }} \
                    -e wp_debug=${{ secrets.WP_DEBUG }} \
                    -v

            - name: Health check
              run: |
                  echo "Waiting for deployment to stabilize..."
                  sleep 30
                  curl -f http://${{ secrets.VPS_HOST }}/health || echo "Health check failed, but deployment may still be successful"

            - name: Deployment summary
              run: |
                  echo "🚀 Deployment completed!"
                  echo "📱 Site URL: https://${{ secrets.DOMAIN_NAME }}"
                  echo "🔧 Traefik Dashboard: https://traefik.${{ secrets.DOMAIN_NAME }}"
                  echo "🖥️  Server IP: ${{ secrets.VPS_HOST }}"
